language: java
sudo: false
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

matrix:
  fast_finish: true
   allow_failures:
      - jdk: oraclejdk11

script:
  - mvn

cache:
  directories:
  - $HOME/.m2
